In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score,confusion_matrix
import joblib as jb

In [8]:
health_data = pd.read_csv("disease_diagnosis.csv")

In [9]:
health_data.columns

Index(['Age', 'Gender', 'Heart_Rate_bpm', 'Body_Temperature_C',
       'Blood_Pressure_mmHg', 'Blood_Pressure_mmHg2', 'Oxygen_Saturation_%',
       'Diagnosis', 'Severity'],
      dtype='object')

In [10]:
health_data.isna().sum()

Age                     378
Gender                  378
Heart_Rate_bpm          378
Body_Temperature_C      378
Blood_Pressure_mmHg       3
Blood_Pressure_mmHg2    378
Oxygen_Saturation_%     378
Diagnosis               378
Severity                378
dtype: int64

In [11]:
health_data.dropna(inplace=True)

In [12]:
health_data.isna().sum()

Age                     0
Gender                  0
Heart_Rate_bpm          0
Body_Temperature_C      0
Blood_Pressure_mmHg     0
Blood_Pressure_mmHg2    0
Oxygen_Saturation_%     0
Diagnosis               0
Severity                0
dtype: int64

In [13]:
health_data

Age  Gender  Heart_Rate_bpm  Body_Temperature_C Blood_Pressure_mmHg  \
0     74.0    Male            69.0                39.4                 132   
1     66.0  Female            95.0                39.0                 174   
2     32.0    Male            77.0                36.8                 136   
3     21.0  Female            72.0                38.9                 147   
4     53.0    Male           100.0                36.6                 109   
...    ...     ...             ...                 ...                 ...   
1994  31.0  Female            93.0                36.4                 139   
1995  23.0  Female            96.0                38.2                 116   
1996  75.0    Male            68.0                36.1                 166   
1997  79.0    Male            73.0                36.7                  91   
1999  45.0  Female           111.0                35.8                 127   

     Blood_Pressure_mmHg2  Oxygen_Saturation_%  Diagnosis  Severity  
0                  132/91                 94.0   Critical  Moderate  
1                  174/98                 98.0    Healthy      Mild  
2                  136/60                 96.0    Healthy      Mild  
3                  147/82                 99.0    Healthy      Mild  
4                 109/106                 92.0    Healthy      Mild  
...                   ...                  ...        ...       ...  
1994               139/92                 99.0  Unhealthy      Mild  
1995              116/113                 98.0    Healthy      Mild  
1996              166/113                 97.0  Unhealthy      Mild  
1997               91/103                 95.0    Healthy      Mild  
1999               127/78                 94.0    Healthy      Mild  

[1622 rows x 9 columns]

In [14]:
X = health_data[['Heart_Rate_bpm', 'Body_Temperature_C', 'Blood_Pressure_mmHg', 'Oxygen_Saturation_%']]
y = health_data['Diagnosis']

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
model = RandomForestClassifier(n_estimators=100, random_state=42)

In [16]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [17]:
y_pred = model.predict(X_test)
y_pred

array(['Healthy', 'Healthy', 'Healthy', 'Healthy', 'Unhealthy', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Unhealthy',
       'Unhealthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Unhealthy', 'Healthy', 'Healthy', 'Critical', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Unhealthy',
       'Critical', 'Healthy', 'Unhealthy', 'Critical', 'Healthy',
       'Unhealthy', 'Healthy', 'Healthy', 'Unhealthy', 'Critical',
       'Unhealthy', 'Healthy', 'Critical', 'Healthy', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Critical', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Critical', 'Healthy', 'Healthy',
       'Critical', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Healthy', 'Unhealthy', 'Healthy', 'Healthy', 'Healthy',
       'Unhealth

In [18]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [19]:
print(accuracy)
print(conf_matrix)
print(class_report)

0.7846153846153846
[[ 17  55   0]
 [ 15 200   0]
 [  0   0  38]]
              precision    recall  f1-score   support

    Critical       0.53      0.24      0.33        72
     Healthy       0.78      0.93      0.85       215
   Unhealthy       1.00      1.00      1.00        38

    accuracy                           0.78       325
   macro avg       0.77      0.72      0.73       325
weighted avg       0.75      0.78      0.75       325



In [20]:
print("Accuracy Of Our Model is :", accuracy*100)

Accuracy Of Our Model is : 78.46153846153847


In [21]:
filename = 'health_monitoring.pkl'
jb.dump(model, filename)

['health_monitoring.pkl']